package Forms;

import Queries.Connect;
import Queries.CustomerQuery;
import Queries.GoldQuery;
import Queries.PriceQuery;
import Queries.UserQuery;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;

public class AllRecordsForm extends java.awt.Dialog {

    Connect mets = new Connect();
    PriceQuery priceQ = new PriceQuery();
    CustomerQuery cusQ = new CustomerQuery();
    GoldQuery goldQ = new GoldQuery();
    UserQuery useQ = new UserQuery();

    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;

    DecimalFormat df2 = new DecimalFormat("####.##");

    public AllRecordsForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        conn = Connect.ConnecrDb();
        setIconImage(mets.myImage("/Images/coin.png"));

        allRecords();
        Colors();
        sumupTotalSale();
        showDate();
    }

    public void allRecords() {
        goldQ.setGoldToTable(gold_table);
    }

    public void Colors() {
        gold_table.getColumnModel().getColumn(0).setCellRenderer(new Connect.CustomRenderer());
        gold_table.getColumnModel().getColumn(1).setCellRenderer(new Connect.CustomRenderer1());
        gold_table.getColumnModel().getColumn(2).setCellRenderer(new Connect.CustomRenderer2());
        gold_table.getColumnModel().getColumn(3).setCellRenderer(new Connect.CustomRenderer3());
        gold_table.getColumnModel().getColumn(4).setCellRenderer(new Connect.CustomRenderer4());
        gold_table.getColumnModel().getColumn(5).setCellRenderer(new Connect.CustomRenderer5());
        gold_table.getColumnModel().getColumn(6).setCellRenderer(new Connect.CustomRenderer6());
        gold_table.getColumnModel().getColumn(7).setCellRenderer(new Connect.CustomRenderer7());
        gold_table.getColumnModel().getColumn(8).setCellRenderer(new Connect.CustomRenderer8());
        gold_table.getColumnModel().getColumn(9).setCellRenderer(new Connect.CustomRenderer9());
        gold_table.getTableHeader().setDefaultRenderer(new Connect.HeaderColor());
    }

    public void sumupTotalSale() {
        double total = 0;
        int rowcount = gold_table.getRowCount();
        double sum = 0;
        for (int i = 0; i < rowcount; i++) {
            sum = sum + Double.parseDouble(gold_table.getValueAt(i, 7).toString());
        }
        total = Double.valueOf(df2.format(sum));
        lbl_totalSales.setText(Double.toString(total));
    }

    public void showDate() {
        goldQ.setGoldToCombo(cmb_date, "Select Date to search");
    }

    public void search() {
        if (cmb_date.getSelectedIndex() <= 0) {
            allRecords();
            Colors();
            sumupTotalSale();
        } else {
            goldQ.setGoldToTableSale(gold_table, cmb_date);
            sumupTotalSale();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        gold_table = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        lbl_totalSales = new javax.swing.JLabel();
        cmb_date = new javax.swing.JComboBox<>();
        btn_refresh = new javax.swing.JButton();

        setResizable(false);
        setTitle("ALL RECORDS FORM");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(248, 203, 117));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ALL RECORDS ON SALES");

        gold_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "Customer", "Top", "Pounds", "Down", "Density", "Karat", "Base", "Money", "Sold By", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(gold_table);
        if (gold_table.getColumnModel().getColumnCount() > 0) {
            gold_table.getColumnModel().getColumn(0).setMaxWidth(25);
            gold_table.getColumnModel().getColumn(1).setPreferredWidth(120);
            gold_table.getColumnModel().getColumn(2).setMaxWidth(70);
            gold_table.getColumnModel().getColumn(3).setMaxWidth(70);
            gold_table.getColumnModel().getColumn(4).setMaxWidth(50);
            gold_table.getColumnModel().getColumn(6).setMaxWidth(50);
            gold_table.getColumnModel().getColumn(7).setMaxWidth(70);
            gold_table.getColumnModel().getColumn(9).setPreferredWidth(100);
            gold_table.getColumnModel().getColumn(10).setPreferredWidth(170);
        }

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Total Money Used For Payment GH₵ :");

        lbl_totalSales.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbl_totalSales.setForeground(new java.awt.Color(102, 0, 0));
        lbl_totalSales.setText("9,000");

        cmb_date.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmb_date.setToolTipText("Select date to search");
        cmb_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_dateActionPerformed(evt);
            }
        });

        btn_refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/refresh.png"))); // NOI18N
        btn_refresh.setToolTipText("Click to refresh");
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 848, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cmb_date, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_refresh)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_totalSales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmb_date)
                    .addComponent(btn_refresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_totalSales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void cmb_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_dateActionPerformed
        search();
    }//GEN-LAST:event_cmb_dateActionPerformed

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        allRecords();
        Colors();
        sumupTotalSale();
        cmb_date.setSelectedIndex(0);
    }//GEN-LAST:event_btn_refreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
        UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AllRecordsForm dialog = new AllRecordsForm(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_refresh;
    private javax.swing.JComboBox<String> cmb_date;
    private javax.swing.JTable gold_table;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_totalSales;
    // End of variables declaration//GEN-END:variables
}
